services:
  db:
    image: mysql:8.0
    container_name: nu-mysql
    restart: always
    environment:
      MYSQL_DATABASE: nu_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: 
      - --innodb_buffer_pool_size=128M
      - --performance_schema=OFF
    deploy:
      resources:
        limits:
          memory: 400M
    
  app:
    build: .
    container_name: nu-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: nu_db
    deploy:
      resources:
        limits:
          memory: 200M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nu-phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 150M